import pandas as pd
import os

def export_reports(cleaned_data_path, segments_data_path, excel_dir):
    """
    Generates Excel reports for business stakeholders.
    """
    print("Generating Excel reports...")
    df = pd.read_csv(cleaned_data_path)
    segments_df = pd.read_csv(segments_data_path)
    
    # Merge risk levels into the main dataframe
    full_df = pd.merge(df, segments_df[['customerID', 'risk_level', 'churn_probability']], on='customerID')
    
    os.makedirs(excel_dir, exist_ok=True)
    
    # REPORT 1: churn_summary.xlsx
    with pd.ExcelWriter(os.path.join(excel_dir, 'churn_summary.xlsx'), engine='openpyxl') as writer:
        # Sheet 1: Executive Summary
        summary_stats = pd.DataFrame({
            'Metric': ['Total Customers', 'Churn Rate (%)', 'Total Monthly Revenue', 'Potential Revenue Loss'],
            'Value': [
                len(df),
                round((df['Churn'] == 'Yes').mean() * 100, 2),
                round(df['MonthlyCharges'].sum(), 2),
                round(df[df['Churn'] == 'Yes']['MonthlyCharges'].sum(), 2)
            ]
        })
        summary_stats.to_excel(writer, sheet_name='Executive Summary', index=False)

        # Sheet 2: Churn Drivers (Categorical breakdown)
        drivers = df.groupby('Contract')['Churn'].value_counts(normalize=True).unstack().fillna(0)
        drivers['Churn_Rate_%'] = round(drivers['Yes'] * 100, 2)
        drivers.to_excel(writer, sheet_name='Churn Drivers')

    # REPORT 2: churn_segments.xlsx
    with pd.ExcelWriter(os.path.join(excel_dir, 'churn_segments.xlsx'), engine='openpyxl') as writer:
        # Sheet 1: Customer Risk Segments
        risk_summary = full_df['risk_level'].value_counts().reset_index()
        risk_summary.columns = ['Risk Level', 'Customer Count']
        risk_summary.to_excel(writer, sheet_name='Customer Risk Segments', index=False)

        # Sheet 2: Revenue Loss Estimation by Segment
        rev_loss = full_df.groupby('risk_level')['MonthlyCharges'].sum().reset_index()
        rev_loss.columns = ['Risk Level', 'Total Monthly Revenue at Risk']
        rev_loss.to_excel(writer, sheet_name='Revenue Loss Estimation', index=False)

    print(f"Excel reports saved to {excel_dir}")

def generate_powerbi_datasets(cleaned_data_path, segments_data_path, pbi_dir):
    """
    Generates specific CSV files for Power BI dashboards.
    """
    print("Generating Power BI datasets...")
    df = pd.read_csv(cleaned_data_path)
    segments_df = pd.read_csv(segments_data_path)
    
    os.makedirs(pbi_dir, exist_ok=True)

    # 1. powerbi_customers.csv (Original cleaned data)
    df.to_csv(os.path.join(pbi_dir, 'powerbi_customers.csv'), index=False)

    # 2. powerbi_churn_metrics.csv (Aggregated metrics)
    metrics = pd.DataFrame({
        'Total_Customers': [len(df)],
        'Churn_Rate': [round((df['Churn'] == 'Yes').mean(), 4)],
        'Total_Revenue': [round(df['MonthlyCharges'].sum(), 2)],
        'Revenue_Lost': [round(df[df['Churn'] == 'Yes']['MonthlyCharges'].sum(), 2)]
    })
    metrics.to_csv(os.path.join(pbi_dir, 'powerbi_churn_metrics.csv'), index=False)

    # powerbi_segments.csv is already generated by churn_prediction.py
    print(f"Power BI datasets saved to {pbi_dir}")

if __name__ == "__main__":
    PROCESSED_DATA_PATH = "data/processed/cleaned_data.csv"
    SEGMENTS_DATA_PATH = "powerbi_dashboard/powerbi_segments.csv"
    EXCEL_DIR = "excel_reports"
    PBI_DIR = "powerbi_dashboard"
    
    export_reports(PROCESSED_DATA_PATH, SEGMENTS_DATA_PATH, EXCEL_DIR)
    generate_powerbi_datasets(PROCESSED_DATA_PATH, SEGMENTS_DATA_PATH, PBI_DIR)
